#!/bin/sh

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM)

echo "[Pre-commit] Running formatting, linting, and tests..."

./mvnw compile

EXIT_CODE=$?

if [ $EXIT_CODE -ne 0 ]; then
  echo "--------------------------------------------------------"
  echo "[ERROR] Pre-commit checks failed."
  echo "Please fix the formatting, linting, or test errors above."
  echo "--------------------------------------------------------"
  exit 1
fi

echo "$STAGED_FILES" | xargs git add
echo "[Pre-commit] All checks passed."
exit 0