FROM eclipse-temurin:17

WORKDIR /app

COPY pom.xml .
COPY src ./src
COPY mvnw ./
COPY .mvn ./.mvn

RUN ./mvnw dependency:go-offline

CMD ["./mvnw", "spring-boot:run", "-Dspring.devtools.restart.enabled=true"]
