name: Bug Report
description: Report a problem or unexpected behavior.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Before opening a new issue, please check the existing `ISSUES` to ensure you are not reporting a duplicate problem. If you find a similar issue, please contribute additional information if necessary.
  - type: textarea
    attributes:
      label: Description
      description: What kind of problem did you encounter? Please describe it clearly and add images if applicable.
      placeholder: |
        I found a problem on the page ... when I was trying to...
        The result was:
        ![image](https://example.com/image)
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce the problem
      description: What are the steps necessary for someone else to encounter the same problem?
      placeholder: |
        1. As a logged-in user, go to page...
        2. Click on...
        3. Do...
        4. Return to ... and see the error.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Possible solution
      description: Have you thought of something that might solve this problem? If so, share below.
      placeholder: |
        Instead of ... we could change ... to...
        Here's an example of what it would look like:
        ![image](https://example.com/image)
